 -- COMENTÁRIOS
 -- COMANDO PARA CRIAR BANCO DE DADOS
 CREATE DATABASE BIBLIOTECA_DA_CORUJA;
 
  -- APAGAR BANCO DE DADOS 
DROP DATABASE BIBLIOTECA_DA_CORUJA;
use BIBLIOTECA_DA_CORUJA;
 -- CRIAR TABELAS
CREATE TABLE FICHA_CLIENTES (
 ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
 NOME VARCHAR(60) NOT NULL,
 CPF VARCHAR (14) NOT NULL UNIQUE,
 ENDERECO VARCHAR(60) NOT NULL,
 EMAIL VARCHAR(100) NOT NULL,
 TELEFONE VARCHAR(15) NOT NULL,
 LIVRO VARCHAR(50) NOT NULL
 );
SHOW TABLES;
-- COMANDO PARA CRIAR  BC
CREATE DATABASE BIBLIOTECA_DA_CORUJA;
CREATE DATABASE IF NOT EXISTS BIBLIOTECA_DA_CORUJA;

-- COMANDA PARA APAGAR BD
DROP DATABASE BIBLIOTECA_DA_CORUJA;

-- ATUALIZAR SCHEMAS

-- COMANDO PARA ATIVAR BD
USE BIBLIOTECA_DA_CORUJA;

-- COMANDO PARA APAGAR TABABELA
DROP DATABASE CLIENTE;

-- COMANDO CRIAR TABELA
CREATE TABLE CLIENTE (
ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
CPF VARCHAR(14) NOT NULL UNIQUE, -- (NOT NULL) SIGINIFICA QUE O ITEM DO CAMPO TEM QUE SER PRENCHIDO. (UNIQUE) SIGINIFICA QUE O ATRIBUTO É UNICO
NOME VARCHAR(60) NOT NULL,
ENDERECO VARCHAR(100),
TELEFONE VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS CLIENTE (
ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
CPF VARCHAR(14) NOT NULL UNIQUE, -- (NOT NULL) SIGINIFICA QUE O ITEM DO CAMPO TEM QUE SER PRENCHIDO. (UNIQUE) SIGINIFICA QUE O ATRIBUTO É UNICO
NOME VARCHAR(60) NOT NULL,
ENDERECO VARCHAR(100),
TELEFONE VARCHAR(20) NOT NULL
);

-- COMANDOS PARA ALTERAR E CORRIGIR
-- ADICIONANDO UM CAMPO (ATRIBUTO) NOVO
ALTER TABLE CLENTE ADD EMAIL VARCHAR(100);

-- MODIFICAR TIPO DE DADOS OU CAMPOS
ALTER TABLE CLIENTES MODIFY EMAIL VARCHAR(150);

-- RENOMEAR TABELAS
RENAME TABLE CLIENTES TO CLENTES2;

-- EXCLUIR ATRIBUTO
ALTER TABLE CLIENTES DROP COLUMN EMAIL;

-- VISUALIZAR TABELAS NO BC
SHOW TABLES;

-- LIMPAR DADOS DA TABELA
TRUNCATE TABLE CLIENTE;


-- TIPO --
-- O (VARCHAR) É USADO PARA SE O ATRIBUTO É ESCRITO
-- O (CHAR) É A MESMA COISA, A DIFERENSA QUE É ALGO MAIS CURTO
-- O (DECIMAL) SERVE PARA COLOCAR VALOR
-- O (DATE) SERVE PARA COLOCAR SÓ A DATA
-- O (DATE TIME) SERVE PARA COLOCAR DATA E HORA

-- ATIVIDADE --

CREATE TABLE PLANOS (
ID_PLANO INT AUTO_INCREMENT PRIMARY KEY,
NOME_DO_PLANO CHAR(50) NOT NULL,
VALOR DECIMAL(5,2) DEFAULT 0.00,
PROFESSOR VARCHAR(100) NOT NULL,
TEMPO_DE_INICIO DATE NOT NULL,
STATUS_CLIENTE ENUM ('PENDENTE', 'ATIVO','INATIVO') DEFAULT 'PENDENTE',
ADICIONAIS CHAR(10) DEFAULT "EXAME",
TEMPO_DE_TERMINO DATE NOT NULL
);

INSERT INTO clientes (ID_CLIENTE,NOME,CPF,TELEFONE,ENDERECO,DATA_NASCIMENTO,STATUS_CLIENTE,DATA_CADRASTRO)
VALUES ('VINICIUS','123.456.789-78', '(19)97894-9141','RUA_SENAI', 'ESTUDANTE', '07/05/2010');

CREATE TABLE FUNCIONARIOS (
  ID_FUNCIONARIO INT PRIMARY KEY,
  EMAIL VARCHAR(255) UNIQUE
  );
  
  insert into FUNCIONARIOS (ID_FUNCIONARIO,EMAIL)
  VALUES (1,'gustavo.c.abreu@edu.senai.br');
  
  -- comando para consultar informacoes na tabela
  SELECT * FROM FUNCIONARIOS;
  
