 -- PROJETO SMARTHCOFFEE
 
-- COMANDO PARA CRIAR O BANCO DE DADOS
CREATE DATABASE IF NOT EXISTS SMARTCOFFEE;

-- ATIVAR O BANCO DE DADOS
USE SMARTCOFFEE;

-- TABELA CLIENTE
CREATE TABLE CLIENTE (
    ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(60) NOT NULL,
    CPF VARCHAR(14) NOT NULL UNIQUE,
    ENDERECO VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    TELEFONE VARCHAR(20) NOT NULL
);

-- TABELA FUNCIONARIO

CREATE TABLE FUNCIONARIO (
    ID_FUNCIONARIO INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(60) NOT NULL,
    CARGO VARCHAR(50) NOT NULL,
    SALARIO DECIMAL(10,2) DEFAULT 0.00,
    DATA_NASCIMENTO DATE,
    ENDERECO VARCHAR(100)
);

-- TABELA CATEGORIA

CREATE TABLE CATEGORIA (
    ID_CATEGORIA INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL UNIQUE
);

-- TABELA FORNECEDOR

CREATE TABLE FORNECEDOR (
    ID_FORNECEDOR INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    TELEFONE VARCHAR(20),
    EMAIL VARCHAR(100),
    ENDERECO VARCHAR(100)
);

-- TABELA PRODUTO

CREATE TABLE PRODUTO (
    ID_PRODUTO INT AUTO_INCREMENT PRIMARY KEY,
    NOME_PRODUTO VARCHAR(100) NOT NULL,
    TIPO VARCHAR(50),
    PRECO DECIMAL(10,2) NOT NULL,
    VALIDADE DATE,
    QUANTIDADE INT DEFAULT 0,

    ID_CATEGORIA INT NOT NULL,
    ID_FORNECEDOR INT NOT NULL,
    

    FOREIGN KEY (ID_CATEGORIA)
        REFERENCES CATEGORIA(ID_CATEGORIA),

    FOREIGN KEY (ID_FORNECEDOR)
        REFERENCES FORNECEDOR(ID_FORNECEDOR)
);

